
paths:
  ROOT_OUT_PATH: './results/'
  ROOT_CHECKPOINT_PATH: './checkpoint/'
  MODELPATH_NORMFLOW: './checkpoint/barc_normflow_pret/rgbddog_v3_model.pt'

smal:
  SMAL_MODEL_TYPE: '39dogs_norm_newv3' 
  SMAL_KEYP_CONF: 'olive'       

optim:
  BATCH_SIZE: 12       

params:
  REF_NET_TYPE: 'multrot01all_res34' 
  REF_DETACH_SHAPE: True
  GRAPHCNN_TYPE: 'multistage_simple'  
  SHAPEREF_TYPE: 'inexistent'  
  ISFLAT_TYPE: 'linear'    

data:
  DATASET: 'ImgCropList'
  VAL_OPT: 'test' 
